### PR TITLE
Add additional option + full list of executables

### PR DESCRIPTION
**Pull request by bergercookie**
* Add `grc_plugin_ignore_execs` option
* Add full list of executables and parse them from separate file

### CODE REVIEW

**Comment by bergercookie** [comment]
Friendly ping :)
Some feedback on this?

**Comment by jspiro** [comment]
How do we get this merged?

**Comment by jspiro** [comment]
In the meantime, using the github cli:
```
$ cd ~/.local/share/omf/pkg/grc
$ gh pr checkout 22
```

**Comment by jspiro** [comment]
Thank you!

**Pull request merged**
