### PR TITLE
Migrate plugin to new omf structure

### PR DESCRIPTION
**Pull request by derekstavis**
This PR migrates this plugin to new package structure. It also does some optimizations over the initial code:
- Includes a list of the built-in colorizers in README
- Split the grc wrapper function from the .load file
- Check if `grc` is available, bail out with error if not
- Wrap completions, as original commands are masked wrapper function

### CODE REVIEW

**Comment by nesl247** [comment]
I think in `grc.wrap.fish`, `$arguments` and `$options` need to be reversed. The problem is with the order it has, you can't override any of the options on the cli at call time.

**Comment by bobthecow** [comment]
:+1:

@derekstavis thoughts on @nesl247's feedback?

I'm inclined to say that we can merge as-is, because this is a direct port of the previous functionality. Then we can worry about making it better. But if you want to take a shot at that as well, that works too :)

**Comment by nesl247** [comment]
@bobthecow Whatever gets it merged in faster. If merging this as-is is the quickest, let's do that, and I'll submit a PR to make the change I was referring to. I actually hadn't used this plugin previously, and didn't notice this was the prior behavior.

**Comment by derekstavis** [comment]
I'd prefer merging as is, because of PR scope. I'm using it daily without issues, so I'm merging it so we can continue improving in next PRs!

**Pull request merged**
